### ISSUE TITLE
PHP script error during install

### ISSUE THREAD

**Issue by Gitoffomalawn** [luketainton/hesk-docker#11]
When installing HESK after spinning up the containers, I receive the following error message during Step 3 of the installation:
```
Deprecated: DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /srv/inc/setup_functions.inc.php on line 86
```
The error doesn't affect the installation process. However, its presence may indicate something isn't exactly right.

**Comment by luketainton** [comment]
This indicates an issue with HESK itself, not the Docker container. I do not maintain HESK so cannot assist with this.
