### ISSUE TITLE
Hesk Version Outdated

### ISSUE THREAD

**Issue by silver-dragon** [luketainton/hesk-docker#44]
According to the install this version is now [outdated](https://www.hesk.com/update.php?v=3.2.5). 

Hesk recommends that Install [3.2.x to 3.4.5 update](https://www.hesk.com/get/hesk32x_to_345)

**Comment by luketainton** [comment]
@silver-dragon As you can tell I've not updated this repo recently and unfortunately I don't currently have time to do so. Some other users have forked this repo already so it might be worth looking at those instead. A good one is https://github.com/trdillon/hesk-docker.
