### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Gitoffomalawn** [luketainton/hesk-docker#6]
Hi, could you maybe provide some information on how to actually use this image? I'd really like to use it to spin up a local instance of Hesk, but I just can't seem to get the container to work.

**Comment by luketainton** [comment]
Hi @Gitoffomalawn,

I've added some usage guidelines to a new README.md file. Please see the feature branch [here](https://github.com/luketainton/hesk-docker/tree/issue-6) and let me know how they work for you.

**Comment by Gitoffomalawn** [comment]
@luketainton Sorry for my late reply. Been pretty busy IRL. 

Your instructions worked just fine, thanks for adding them. I don't know if it's within scope of this project, but you could consider adding a DB image to a Docker Compose to make the whole setup easier. 

Otherwise, thanks once again.

**Comment by luketainton** [comment]
@Gitoffomalawn I already did that, should be in the `docker-compose.example.yml` file :)

**Comment by Gitoffomalawn** [comment]
@luketainton Oh, nice. I'll have a look.
